language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

install:
    - composer install --no-interaction

cache:
    directories:
        - vendor

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpstan analyze --configuration=phpstan.neon --level=max --no-interaction --no-progress src/ tests/
    - php -derror_reporting=E_ALL ./vendor/bin/phpunit
